In [7]:
require("reticulate")
source_python("pickle_reader.py")
ndvi_1994_data <- read_pickle_file("../../working/ndvi_1994_data")

Loading required package: reticulate



In [8]:
library(doParallel)
library(foreach)

# Define the number of cores (adjust as needed)
num_cores <- 4

# Initialize parallel processing
cl <- makeCluster(num_cores)
registerDoParallel(cl)

# Define the dimensions of the matrix
matrix_rows <- 30
total_iterations <- 8  # Assuming you have defined 'total_iterations'

# Create a progress bar function (optional)
create_pb <- function(total) {
  pb <- txtProgressBar(min = 0, max = total, style = 3)
  on.exit(close(pb))
  return(pb)
}

# Define a function to fill a portion of the matrix and return results
calculate_recovery <- function(data, t) {
  # Perform your data processing here
  
  # For example:
  local_matrix <- matrix(0, nrow = 1, ncol = 5)
  y_result <- 123  # Replace with your actual y result
  
  # Return results as a named list
  return(list(local_matrix = local_matrix, y = y_result))
}

# Create the progress bar (optional)
# pb <- create_pb(total_iterations)

# Initialize empty lists to accumulate results
ci_list <- list()
y_list <- list()

# Run the loop in parallel
foreach(i = 1:total_iterations) %dopar% {
  data <- ndvi_1994_data[i]
  data <- matrix(unlist(data), nrow = matrix_rows)
  
  # Perform the work and fill the local matrix, and get y
  results <- calculate_recovery(data, t)
  
  ci_list[[i]] <- results$local_matrix
  y_list[[i]] <- results$y
  
  # Update the progress bar (optional)
  # setTxtProgressBar(pb, getTxtProgressBar(pb) + 1)
  
  return(results)
}

# Stop parallel processing
stopCluster(cl)

[[1]]
[[1]]$local_matrix
     [,1] [,2] [,3] [,4] [,5]
[1,]    0    0    0    0    0

[[1]]$y
[1] 123


[[2]]
[[2]]$local_matrix
     [,1] [,2] [,3] [,4] [,5]
[1,]    0    0    0    0    0

[[2]]$y
[1] 123


[[3]]
[[3]]$local_matrix
     [,1] [,2] [,3] [,4] [,5]
[1,]    0    0    0    0    0

[[3]]$y
[1] 123


[[4]]
[[4]]$local_matrix
     [,1] [,2] [,3] [,4] [,5]
[1,]    0    0    0    0    0

[[4]]$y
[1] 123


[[5]]
[[5]]$local_matrix
     [,1] [,2] [,3] [,4] [,5]
[1,]    0    0    0    0    0

[[5]]$y
[1] 123


[[6]]
[[6]]$local_matrix
     [,1] [,2] [,3] [,4] [,5]
[1,]    0    0    0    0    0

[[6]]$y
[1] 123


[[7]]
[[7]]$local_matrix
     [,1] [,2] [,3] [,4] [,5]
[1,]    0    0    0    0    0

[[7]]$y
[1] 123


[[8]]
[[8]]$local_matrix
     [,1] [,2] [,3] [,4] [,5]
[1,]    0    0    0    0    0

[[8]]$y
[1] 123

In [12]:
res = calculate_recovery(data,t)
res$local_matrix

[,1] [,2] [,3] [,4] [,5]
[1,] 0    0    0    0    0

In [58]:
library(doParallel)
library(foreach)

# Define the number of cores (adjust as needed)
num_cores <- 4

# Initialize parallel processing
cl <- makeCluster(num_cores)
registerDoParallel(cl)

# Define the dimensions of the matrix
matrix_rows <- 30
total_iterations <- 8  # Assuming you have defined 'total_iterations'

# Create a progress bar function (optional)
create_pb <- function(total) {
  pb <- txtProgressBar(min = 0, max = total, style = 3)
  on.exit(close(pb))
  return(pb)
}

# Define a function to fill a portion of the matrix and return results
calculate_recovery <- function(data, t) {
  # Perform your data processing here
  
  # For example:
  local_matrix <- matrix(0, nrow = 1, ncol = 5)
  y_result <- 123  # Replace with your actual y result
  
  # Return results as a named list
  return(list(local_matrix = local_matrix, y = y_result))
}

# Create the progress bar (optional)
# pb <- create_pb(total_iterations)

# Run the loop in parallel and accumulate results as a list
result_list <- foreach(i = 1:total_iterations, .combine = 'c') %dopar% {
  data <- ndvi_1994_data[i]
  data <- matrix(unlist(data), nrow = matrix_rows)
  
  # Perform the work and fill the local matrix, and get y
  results <- calculate_recovery(data, t)
  
  # Update the progress bar (optional)
  # setTxtProgressBar(pb, getTxtProgressBar(pb) + 1)
  
  return(results)
}

# Stop parallel processing
stopCluster(cl)

# Split 'result_list' into individual results
result_list <- split(result_list, rep(1:total_iterations, each = 1))

# Extract 'ci_list' and 'y_list' from the 'result_list'
ci_list <- lapply(result_list, function(result) result$local_matrix)
y_list <- lapply(result_list, function(result) result$y)

In [59]:
ci_matrix <- do.call(rbind, ci_list)
ci_matrix

[,1] [,2] [,3] [,4] [,5]
[1,] 0    0    0    0    0   
[2,] 0    0    0    0    0   
[3,] 0    0    0    0    0   
[4,] 0    0    0    0    0

In [60]:
ci_list

$`1`
     [,1] [,2] [,3] [,4] [,5]
[1,]    0    0    0    0    0

$`2`
NULL

$`3`
     [,1] [,2] [,3] [,4] [,5]
[1,]    0    0    0    0    0

$`4`
NULL

$`5`
     [,1] [,2] [,3] [,4] [,5]
[1,]    0    0    0    0    0

$`6`
NULL

$`7`
     [,1] [,2] [,3] [,4] [,5]
[1,]    0    0    0    0    0

$`8`
NULL

In [26]:
ci_list

[[1]]
NULL

[[2]]
     [,1] [,2] [,3] [,4] [,5]
[1,]    0    0    0    0    0